jobs/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

market/urls.py
from django.conf.urls import url

from . import views

app_name = 'market'
urlpatterns = [
    url(r'^$', views.HomePageView.as_view(), name='index'),
]

market/models.py
from __future__ import unicode_literals
import os

from django.db import models
from django.conf import settings

from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from versatileimagefield.fields import VersatileImageField
from versatileimagefield.placeholder import OnDiscPlaceholderImage

DEFAULT_KIND_CHOICES = (
    (0, _('Default product'),),
)

PRODUCT_KINDS_CHOICES = getattr(settings, 'MARKET_PRODUCT_KIND_CHOICES', DEFAULT_KIND_CHOICES)


@python_2_unicode_compatible
class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=False, null=False)
    name = models.CharField(
        _("Name of the product"),
        max_length=300, blank=False, null=False,
    )

    quantity = models.PositiveIntegerField(_("Amount in storage"), default=0, blank=True, null=False)

    image = VersatileImageField(_('product userpic'),
                                blank=True, null=True,
                                upload_to="products/",
                                placeholder_image=OnDiscPlaceholderImage(
                                    path=os.path.join(
                                        os.path.dirname(os.path.abspath(__file__)),
                                        'static/market/img/placeholder.png'
                                    ))
                                )
    status = models.IntegerField(_("product status"), default=1, blank=True, null=False, )

    kind = models.PositiveIntegerField(default=PRODUCT_KINDS_CHOICES[0][0], choices=PRODUCT_KINDS_CHOICES,
                                       blank=True, null=False,)

    created_at = models.DateTimeField(
        _("Created at"),
        auto_now_add=True
    )

    updated_at = models.DateTimeField(
        _("Updated at"),
        auto_now=True
    )

    active = models.BooleanField(
        _("Active"),
        default=False, help_text=_("Shows whether product is visible to visitors")
    )

    price = models.DecimalField(_("Price"),
                                max_digits=10, blank=False, default=0, null=False, decimal_places=3)

    description = models.TextField(_("product description"), blank=True, null=True)

    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def __str__(self):
        return '%s' % (self.name,)


@python_2_unicode_compatible
class Attribute(models.Model):
    name = models.CharField(_("Verbose name of attribute, i.e. Color, Fasion, HDD Size"),
                            max_length=200, blank=False, null=False,)
    key = models.CharField(_('short search key'),
                           max_length=200, blank=False, null=False, unique=True, db_index=True,)

    class Meta:
        verbose_name = _("Product Attribute")
        verbose_name_plural = _("Product Attributes")

    def __str__(self):
        return '%s' % (self.name, )


@python_2_unicode_compatible
class AttributeValue(models.Model):
    """
    This model provides relation between attribute
    and attribute value to particular product.
    """
    product = models.ForeignKey(Product, blank=False, null=False,)
    attribute = models.ForeignKey(Attribute, blank=False, null=False,)
    value = models.CharField(max_length=200, blank=False, null=False)

    class Meta:
        verbose_name = _("Product Attribute Value")
        verbose_name_plural = _("Product Attribute Values")

    def __str__(self):
        return '%s' % (self.name,)

market/forms.py
from django import forms

from .models import (
    Product, Attribute, AttributeValue,
)


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product

market/views.py
from __future__ import unicode_literals

from django.views import generic


class HomePageView(generic.TemplateView):
    template_name = 'market/index.html'

market/templates/market/base.html
<!doctype html>
<html lang="en" class="no-js">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Online Store</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'market/css/style.css' %}">
    <script src="{% static 'market/js/src/modernizr-custom.js' %}"></script>
</head>
<body>
    <!-- navigation -->
	<nav class="pages-nav">
		<div class="pages-nav__item"><a class="link link--page" href="#page-home"></a></div>
		<div class="pages-nav__item"><a class="link link--page" href="#page-docu"></a></div>
		<div class="pages-nav__item"><a class="link link--page" href="#page-manuals"></a></div>
		<div class="pages-nav__item"><a class="link link--page" href="#page-home">Продукция</a></div>
		<div class="pages-nav__item"><a class="link link--page" href="#page-custom">Доставка</a></div>
		<div class="pages-nav__item"><a class="link link--page" href="#page-training">Контакты</a></div>
		<div class="pages-nav__item pages-nav__item--small"><a class="link link--page link--faded" href="#page-buy">Войти/Зарегестрироваться</a></div>
		<div class="pages-nav__item pages-nav__item--small"><a class="link link--page link--faded" href="#page-blog">Blog &amp; News</a></div>
		<div class="pages-nav__item pages-nav__item--small"><a class="link link--page link--faded" href="#page-contact">Contact</a></div>
		<div class="pages-nav__item pages-nav__item--social">
			<a class="link link--social link--faded" href="#"><i class="fa fa-twitter"></i><span class="text-hidden">Twitter</span></a>
			<a class="link link--social link--faded" href="#"><i class="fa fa-linkedin"></i><span class="text-hidden">LinkedIn</span></a>
			<a class="link link--social link--faded" href="#"><i class="fa fa-facebook"></i><span class="text-hidden">Facebook</span></a>
			<a class="link link--social link--faded" href="#"><i class="fa fa-youtube-play"></i><span class="text-hidden">YouTube</span></a>
		</div>
	</nav>
	<!-- /navigation-->
	<!-- pages stack -->
	<div class="pages-stack">
		<!-- page -->
		<div class="page" id="page-home">
			<div class="page-content">

                <ul class="categories-list">
                    <li><a href="#">Чехлы</a></li>
                    <li><a href="#">Карты памяти</a></li>
                    <li><a href="#">Защитные пленки</a></li>
                    <li><a href="#">Наушники</a></li>
                    <li><a href="#">Аккумуляторы</a></li>
                    <li><a href="#">Зарядные устройства</a></li>
                    <li><a href="#">Док станции</a></li>
                </ul>
                <div class="products">
                    <div class="product">
                        <div class="product-image-wrapper">
                            <img src="{% static "market/img/examples/products/1-1.jpg" %}" class="product-image" alt="">
                        </div>
                        <div class="product-caption">
                            Чехол-книжка Samsung Flip Wallet для Samsung Galaxy A3
                        </div>
                    </div>
                </div>
            </div>
		</div>
		<!-- /page -->
		<div class="page" id="page-docu">
			<header class="bp-header cf">
				<h1 class="bp-header__title">Documentation</h1>
				<p class="bp-header__desc">Based on Ilya Kostin's Dribbble shot <a href="https://dribbble.com/shots/2286042-Stacked-navigation">Stacked navigation</a></p>
				<p class="info">
					"We cannot have peace among men whose hearts find delight in killing any living creature." &mdash; Rachel Carson
				</p>
			</header>
			<img class="poster" src="{% static "market/img/6.jpg" %}" alt="img06" />
		</div>
		<div class="page" id="page-manuals">
			<header class="bp-header cf">
				<h1 class="bp-header__title">Manuals</h1>
				<p class="bp-header__desc">Based on Ilya Kostin's Dribbble shot <a href="https://dribbble.com/shots/2286042-Stacked-navigation">Stacked navigation</a></p>
				<p class="info">
					"When you adopt a vegan diet we make a connection, you don't go back, it is not a diet, it is a lifestyle." &mdash; Freelee Frugivore
				</p>
			</header>
			<img class="poster" src="{% static "market/img/2.jpg" %}" alt="img02" />
		</div>
		<div class="page" id="page-software">
			<header class="bp-header cf">
				<h1 class="bp-header__title">Software &amp; Downloads</h1>
				<p class="bp-header__desc">Based on Ilya Kostin's Dribbble shot <a href="https://dribbble.com/shots/2286042-Stacked-navigation">Stacked navigation</a></p>
				<p class="info">
					"I decided to pick the diet that I thought would maximize my chances of long-term survival." &mdash; Al Gore
				</p>
			</header>
			<img class="poster" src="{% static "market/img/3.jpg" %}" alt="img03" />
		</div>
		<div class="page" id="page-custom">
			<header class="bp-header cf">
				<h1 class="bp-header__title">Customization &amp; Settings</h1>
				<p class="bp-header__desc">Based on Ilya Kostin's Dribbble shot <a href="https://dribbble.com/shots/2286042-Stacked-navigation">Stacked navigation</a></p>
				<p class="info">
					"You have to make a conscious decision to change for your own well-being, that of your family and your country." &mdash;Bill Clinton
				</p>
			</header>
			<img class="poster" src="{% static "market/img/4.jpg" %}" alt="img04" />
		</div>
		<div class="page" id="page-training">
			<header class="bp-header cf">
				<h1 class="bp-header__title">Training &amp; Learning Center</h1>
				<p class="bp-header__desc">Based on Ilya Kostin's Dribbble shot <a href="https://dribbble.com/shots/2286042-Stacked-navigation">Stacked navigation</a></p>
				<p class="info">
					"The moment I began to understand what was going on with the treatment of animals, it led me more and more in the way of the path I am [on] now, which is a complete vegan." &mdash; Bryan Adams
				</p>
			</header>
			<img class="poster" src="{% static "market/img/5.jpg" %}" alt="img05" />
		</div>
		<div class="page" id="page-buy">
			<header class="bp-header cf">
				<h1 class="bp-header__title">Where to buy</h1>
				<p class="bp-header__desc">Based on Ilya Kostin's Dribbble shot <a href="https://dribbble.com/shots/2286042-Stacked-navigation">Stacked navigation</a></p>
				<p class="info">
					"When people ask me why I don't eat meat or any other animal products, I say, 'Because they are unhealthy and they are the product of a violent and inhumane industry.'" &mdash;
				</p>
			</header>
			<img class="poster" src="{% static "market/img/6.jpg" %}" alt="img06" />
		</div>
		<div class="page" id="page-blog">
			<header class="bp-header cf">
				<h1 class="bp-header__title">Blog &amp; News</h1>
				<p class="bp-header__desc">Based on Ilya Kostin's Dribbble shot <a href="https://dribbble.com/shots/2286042-Stacked-navigation">Stacked navigation</a></p>
				<p class="info">
					"The question is not, 'Can they reason?' nor, 'Can they talk?' but rather, 'Can they suffer?" &mdash; Jeremy Bentham
				</p>
			</header>
			<img class="poster" src="{% static "market/img/1.jpg" %}" alt="img01" />
		</div>
		<div class="page" id="page-contact">
			<header class="bp-header cf">
				<h1 class="bp-header__title">Contact</h1>
				<p class="bp-header__desc">Based on Ilya Kostin's Dribbble shot <a href="https://dribbble.com/shots/2286042-Stacked-navigation">Stacked navigation</a></p>
				<p class="info">
					"Man is the only animal that can remain on friendly terms with the victims he intends to eat until he eats them." &mdash; Samuel Butler
				</p>
			</header>
			<img class="poster" src="{% static "market/img/4.jpg" %}" alt="img04" />
		</div>
	</div>
	<!-- /pages-stack -->
	<div class="top-nav">
        <button class="menu-button"><span>Menu</span></button>
        <h3 class="logo"><a href="{% url 'market:index' %}" class="link">Online Store</a></h3>
        <div class="top-form">
             <span class="input-addon"><i class="fa fa-search"></i></span>
            <input type="text" class="search-global" />
        </div>
        <div class="cart">
            <a href="#" class="cart-toggler">
                <i class="fa fa-cart"></i>
            </a>
        </div>

    </div>
<script src="{% static 'market/js/dist/index.js' %}"></script>
</body>
</html>

market/templates/market/index.html
{% extends 'market/base.html' %}